version: '3.1'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    volumes:
      - '/var/lib/mysql:/var/lib/mysql'
    ports:
      - '3306:3306'
  web:
    build: .
    ports:
      - '4000:4000'